package com.pilipili.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setAccount(String account) {
		set("account", account);
		return (M)this;
	}
	
	public String getAccount() {
		return getStr("account");
	}

	public M setPassword(String password) {
		set("password", password);
		return (M)this;
	}
	
	public String getPassword() {
		return getStr("password");
	}

	public M setAvatarUrl(String avatarUrl) {
		set("avatarUrl", avatarUrl);
		return (M)this;
	}
	
	public String getAvatarUrl() {
		return getStr("avatarUrl");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setSex(Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public Integer getSex() {
		return getInt("sex");
	}

	public M setSign(String sign) {
		set("sign", sign);
		return (M)this;
	}
	
	public String getSign() {
		return getStr("sign");
	}

}
