package com.pilipili.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setUserId(Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public Long getUserId() {
		return getLong("userId");
	}

	public M setInfoPictureId(Long infoPictureId) {
		set("infoPictureId", infoPictureId);
		return (M)this;
	}
	
	public Long getInfoPictureId() {
		return getLong("infoPictureId");
	}

	public M setComment(String comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public String getComment() {
		return getStr("comment");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public M setReplyNum(Integer replyNum) {
		set("replyNum", replyNum);
		return (M)this;
	}
	
	public Integer getReplyNum() {
		return getInt("replyNum");
	}

}
