package com.pilipili.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInfoPicture<M extends BaseInfoPicture<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setUserId(Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public Long getUserId() {
		return getLong("userId");
	}

	public M setUrl(String url) {
		set("url", url);
		return (M)this;
	}
	
	public String getUrl() {
		return getStr("url");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public M setShare(Integer share) {
		set("share", share);
		return (M)this;
	}
	
	public Integer getShare() {
		return getInt("share");
	}

	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}
	
	public String getTitle() {
		return getStr("title");
	}

	public M setIntro(String intro) {
		set("intro", intro);
		return (M)this;
	}
	
	public String getIntro() {
		return getStr("intro");
	}

	public M setDeletehash(String deletehash) {
		set("deletehash", deletehash);
		return (M)this;
	}
	
	public String getDeletehash() {
		return getStr("deletehash");
	}

}
