package com.pilipili.model;

import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;
import com.pilipili.model.base.BaseInfoPicture;

import java.io.IOException;
import java.io.StringReader;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InfoPicture extends BaseInfoPicture<InfoPicture> {
    public static final String ID = "id";
    public static final String USER_ID = "userId";
    public static final String URL = "url";
    public static final String DATE = "date";
    public static final String SHARE = "share";
    public static final String TITLE = "title";
    public static final String INTRO = "intro";
    public static final String DELETEHASH = "deletehash";

    public static final int SHARE_TRUE = 1;
    public static final int SHARE_FALSE = 0;

    public static final InfoPicture dao = new InfoPicture().dao();

    public static JsonWriter toJson(InfoPicture infoPicture, JsonWriter jsonWriter) throws IOException {
        if (infoPicture == null || jsonWriter == null) {
            return jsonWriter;
        }

        return jsonWriter.beginObject()
                .name(ID).value(infoPicture.getId())
                .name(USER_ID).value(infoPicture.getUserId())
                .name(URL).value(infoPicture.getUrl())
                .name(DATE).value(infoPicture.getDate().getTime())
                .name(SHARE).value(infoPicture.getShare() == SHARE_TRUE ? true : false)
                .name(TITLE).value(infoPicture.getTitle())
                .name(INTRO).value(infoPicture.getIntro())
                .name(DELETEHASH).value(infoPicture.getDeletehash())
                .endObject();
    }

    public static InfoPicture fromJson(String json) throws IOException {
        if (json == null) {
            return null;
        }

        InfoPicture infoPicture = new InfoPicture();
        JsonReader jsonReader = new JsonReader(new StringReader(json));

        jsonReader.beginObject();
        while (jsonReader.hasNext()) {
            switch (jsonReader.nextName()) {
                case ID: {
                    infoPicture.setId(jsonReader.nextLong());
                    break;
                }
                case USER_ID: {
                    infoPicture.setUserId(jsonReader.nextLong());
                    break;
                }
                case URL: {
                    infoPicture.setUrl(jsonReader.nextString());
                    break;
                }
                case DATE: {
                    if (jsonReader.peek() == JsonToken.NULL) {
                        jsonReader.nextNull();
                        infoPicture.setDate(null);
                    } else {
                        infoPicture.setDate(new Date(jsonReader.nextLong()));
                    }
                    break;
                }
                case SHARE: {
                    infoPicture.setShare(jsonReader.nextBoolean() ? SHARE_TRUE : SHARE_FALSE);
                    break;
                }
                case TITLE: {
                    infoPicture.setTitle(jsonReader.nextString());
                    break;
                }
                case INTRO: {
                    if (jsonReader.peek() == JsonToken.NULL) {
                        jsonReader.nextNull();
                        infoPicture.setIntro("");
                    } else {
                        infoPicture.setIntro(jsonReader.nextString());
                    }
                    break;
                }
                case DELETEHASH: {
                    infoPicture.setDeletehash(jsonReader.nextString());
                    break;
                }
                default: {
                    jsonReader.skipValue();
                    break;
                }
            }
        }
        jsonReader.endObject();
        jsonReader.close();

        return infoPicture;
    }
}
